# Generated by Django 3.0.3 on 2020-03-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogInfo',
        ),
    ]
